name: Test building site with conda environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, macos, windows]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: conda-incubator/setup-miniconda@d2e6a045a86077fb6cad6f5adf368e9076ddaa8d  # v3.1.0
        with:
          auto-update-conda: true
          activate-environment: numpy-tutorials
          environment-file: environment.yml
          miniforge-version: latest
          use-mamba: true
          python-version: "3.11"
          auto-activate-base: false
      - name: inspect and build
        id: build_step
        continue-on-error: true
        run: |
          conda info
          conda list
          make -C site/ SPHINXOPTS="-nWT --keep-going" html

      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b  # v4.5.0
        with:
          name: sphinx-build-artifact
          path: site/_build/html/reports

      - name: fail on build errors
        if: steps.build_step.outcome != 'success'
        run: exit 1
