name: Test building site with conda environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, macos, windows]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0
      - uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca  # v3.0.4
        with:
          auto-update-conda: true
          activate-environment: numpy-tutorials
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          python-version: "3.11"
          auto-activate-base: false
      - name: inspect and build
        id: build_step
        continue-on-error: true
        run: |
          conda info
          conda list
          make -C site/ SPHINXOPTS="-nWT --keep-going" html

      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874  # v4.4.0
        with:
          name: sphinx-build-artifact
          path: site/_build/html/reports

      - name: fail on build errors
        if: steps.build_step.outcome != 'success'
        run: exit 1
